#############################################################################
# Makefile for building: Qt-notepad-exe
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  Qt-notepad/Qt-notepad.pro
# Template: app
# Command: /home/yeray/Qt/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-notepad/Qt-notepad.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.2.1/gcc_64/mkspecs/linux-g++ -IQt-notepad -I../../../Qt/5.2.1/gcc_64/include -I../../../Qt/5.2.1/gcc_64/include/QtWidgets -I../../../Qt/5.2.1/gcc_64/include/QtGui -I../../../Qt/5.2.1/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/yeray/Qt/5.2.1/gcc_64 -Wl,-rpath,/home/yeray/Qt/5.2.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/yeray/Qt/5.2.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/yeray/Qt/5.2.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Qt-notepad/main.cpp \
		Qt-notepad/notepadwindow.cpp qrc_resources.cpp \
		moc_notepadwindow.cpp
OBJECTS       = main.o \
		notepadwindow.o \
		qrc_resources.o \
		moc_notepadwindow.o
DIST          = ../../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/uic.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		Qt-notepad/Qt-notepad/Qt-notepad.pro \
		Qt-notepad/Qt-notepad/resources.qrc \
		Qt-notepad/Qt-notepad.pro
QMAKE_TARGET  = Qt-notepad-exe
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Qt-notepad-exe


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Qt-notepad/Qt-notepad.pro ../../../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		Qt-notepad/Qt-notepad.pro \
		Qt-notepad/resources.qrc \
		/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Widgets.prl \
		/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Gui.prl \
		/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-notepad/Qt-notepad.pro
../../../Qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/uic.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.2.1/gcc_64/mkspecs/features/lex.prf:
Qt-notepad/Qt-notepad.pro:
Qt-notepad/resources.qrc:
/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Widgets.prl:
/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Gui.prl:
/home/yeray/Qt/5.2.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Qt-notepad/Qt-notepad.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Qt-notepad-exe1.0.0 || mkdir -p .tmp/Qt-notepad-exe1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/resources.qrc .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/notepadwindow.h .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/main.cpp Qt-notepad/notepadwindow.cpp .tmp/Qt-notepad-exe1.0.0/ && (cd `dirname .tmp/Qt-notepad-exe1.0.0` && $(TAR) Qt-notepad-exe1.0.0.tar Qt-notepad-exe1.0.0 && $(COMPRESS) Qt-notepad-exe1.0.0.tar) && $(MOVE) `dirname .tmp/Qt-notepad-exe1.0.0`/Qt-notepad-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt-notepad-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: Qt-notepad/resources.qrc \
		Qt-notepad/new.png \
		Qt-notepad/undo.png \
		Qt-notepad/redo.png \
		Qt-notepad/open.png \
		Qt-notepad/save.png
	/home/yeray/Qt/5.2.1/gcc_64/bin/rcc -name resources Qt-notepad/resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_notepadwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_notepadwindow.cpp
moc_notepadwindow.cpp: ../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QPlainTextEdit \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qplaintextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextdocument.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextformat.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qglyphrun.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrawfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontdatabase.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenu \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenu.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qaction.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenuBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenubar.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QAction \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFileDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/QFile \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFontDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfontdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QClipboard \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qclipboard.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QKeySequence \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QToolBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtoolbar.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QIcon \
		Qt-notepad/notepadwindow.h
	/home/yeray/Qt/5.2.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) Qt-notepad/notepadwindow.h -o moc_notepadwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: Qt-notepad/main.cpp Qt-notepad/notepadwindow.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QPlainTextEdit \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qplaintextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextdocument.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextformat.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qglyphrun.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrawfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontdatabase.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenu \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenu.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qaction.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenuBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenubar.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QAction \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFileDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/QFile \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFontDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfontdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QClipboard \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qclipboard.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QKeySequence \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QToolBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtoolbar.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QIcon \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Qt-notepad/main.cpp

notepadwindow.o: Qt-notepad/notepadwindow.cpp Qt-notepad/notepadwindow.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QPlainTextEdit \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qplaintextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextdocument.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextoption.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextcursor.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextformat.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qpen.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qabstracttextdocumentlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qtextlayout.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qglyphrun.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qrawfont.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qfontdatabase.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenu \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenu.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qaction.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMenuBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmenubar.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QAction \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFileDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfiledialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtCore/QFile \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QFontDialog \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qfontdialog.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QClipboard \
		../../../Qt/5.2.1/gcc_64/include/QtGui/qclipboard.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QKeySequence \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QMessageBox \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qmessagebox.h \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/QToolBar \
		../../../Qt/5.2.1/gcc_64/include/QtWidgets/qtoolbar.h \
		../../../Qt/5.2.1/gcc_64/include/QtGui/QIcon
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notepadwindow.o Qt-notepad/notepadwindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_notepadwindow.o: moc_notepadwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notepadwindow.o moc_notepadwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

